# Generated by Django 3.2.5 on 2021-07-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_email_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='base64_certificate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='certificate_password',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_hom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uf',
            field=models.IntegerField(choices=[(12, 'Ac'), (27, 'Al'), (13, 'Am'), (16, 'Ap'), (29, 'Ba'), (23, 'Ce'), (53, 'Df'), (32, 'Es'), (52, 'Go'), (21, 'Ma'), (31, 'Mg'), (50, 'Ms'), (51, 'Mt'), (15, 'Pa'), (25, 'Pb'), (26, 'Pe'), (22, 'Pi'), (41, 'Pr'), (33, 'Rj'), (24, 'Rn'), (11, 'Ro'), (14, 'Rr'), (43, 'Rs'), (42, 'Sc'), (28, 'Se'), (35, 'Sp'), (17, 'To')], default=21),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=14, unique=True, verbose_name='cnpj'),
        ),
    ]
